AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Weather API on AWS Lambda

Parameters:
  GroqApiKey:
    Type: String
    NoEcho: true
  JwtSecret:
    Type: String
    NoEcho: true

Resources:
  WeatherApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/lambda.handler
      Runtime: nodejs22.x
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          GROQ_API_KEY: !Ref GroqApiKey
          JWT_SECRET: !Ref JwtSecret
          AI_MODEL: "llama-3.3-70b-versatile"
          AI_BASE_URL: "https://api.groq.com/openai/v1"
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
